name: CI Pipeline

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    pull_request:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Run `npm test`
        run: npm test
      
      - name: Build image
        uses: bitovi/github-actions-docker-publish@main
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}